// Code generated by mockery v2.42.0. DO NOT EDIT.

package gcfmocks

import (
	context "context"

	types "github.com/aws-samples/serverless-go-demo/types"
	mock "github.com/stretchr/testify/mock"
)

// MockBus is an autogenerated mock type for the Bus type
type MockBus struct {
	mock.Mock
}

// Put provides a mock function with given fields: _a0, _a1
func (_m *MockBus) Put(_a0 context.Context, _a1 []types.Event) ([]types.FailedEvent, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 []types.FailedEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.Event) ([]types.FailedEvent, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []types.Event) []types.FailedEvent); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.FailedEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []types.Event) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockBus creates a new instance of MockBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBus {
	mock := &MockBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
